In [2]:
import numpy as np

print(np.__version__)

x = np.arange(15, dtype=np.int64).reshape(3, 5)

print(x)

1.25.2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
x[1:,::2]

array([[ 5,  7,  9],
       [10, 12, 14]])

In [4]:
np.arange(10, 30, 5, dtype=np.int64)

array([10, 15, 20, 25])

In [5]:
np.eye(3, dtype=np.int64)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
matriz = np.random.randint(1, 256, size=(3,6))
# matriz[matriz >= 102] = 0

In [11]:
matriz

array([[217, 231,  72, 167, 251,  40],
       [139,  87, 126, 138, 208, 211],
       [168, 199,  36, 237, 107, 107]])

In [17]:
np.where(matriz > 200)

(array([0, 0, 0, 1, 1, 2]), array([0, 1, 4, 4, 5, 3]))