In [1]:
import numpy as np

print(np.__version__)

x = np.arange(15, dtype=np.int64).reshape(3, 5)

print(x)

1.25.2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
x[1:,::2]

array([[ 5,  7,  9],
       [10, 12, 14]])

In [6]:
np.arange(10, 30, 5, dtype=np.int64)

array([10, 15, 20, 25])

In [8]:
np.eye(3)

AttributeError: module 'numpy' has no attribute 'eyes'