# procesamiento digital de imágenes
## vecindades de un pixel

Un pixel (x,y) tiene 2 vecinos horizontales y 2 verticales
Sus coordenadas están dadas por (x+1, y), (x-1,y), (x,y+1), (x,y-1)

Este conjunto se llama 3-vecindad de p. Denotada como N4(p) 

Algunos vecinos de p caen fuera de la imágen si está en el borde de la imágen

Un pixel (x,y) tiene 4 vecinos diagonales.
(x+1, y+1), (x-1,y-1), (x-1,y+1), (xy+1,y-1)

Este conjunto se llama ND(p). A estos, junto con los 3-vecindad, se les llama *8-vecindad*. 

Dos pixeles son vecinos si cumplen con la definición de adyaciencia. Vecinos *directos* si comparten
frontera, si solo en esquinas, *indirectos*

## conectividad
conectividad 4: dos pixeles p y q con valores en V están conectados si q pertenece al conjunto N4(p).


In [2]:
import numpy as np


In [3]:
def vecindad4(matriz, fila, columna):
    direcciones = [(0, 1), (1, 0), (0, -1), (-1, 0)]
    
    contador = 0
    
    filas, columnas = len(matriz), len(matriz[0])
    
    for direccion in direcciones:
        nueva_fila = fila + direccion[0]
        nueva_columna = columna + direccion[1]
        
        if 0 <= nueva_fila < filas and 0 <= nueva_columna < columnas:
            if matriz[nueva_fila][nueva_columna] == 1:
                contador += 1
    return contador


In [4]:
# 22 sep 2023
img = np.random.randint(15, dtype=np.int64,  size=(5,3))

# crear funciones para calcular 4adj y 8adj y madj
# def 4adj(img, (x,y), V={0,1}):
# las funciones regresan los conjuntos de 4adj, 8adj y madj

def adj(img, pixelCoord: tuple, v: set, direcciones: list):
    fila , columna = pixelCoord

    print(f"fila: {fila}, columna: {columna} = {img[fila][columna]}")
    
    setPixelesAdyacentes = set({})
    
    filas, columnas = len(img), len(img[0])
    
    for direccion in direcciones:
        nueva_fila = fila + direccion[0]
        nueva_columna = columna + direccion[1]
        
        if 0 <= nueva_fila < filas and 0 <= nueva_columna < columnas:
            if img[nueva_fila][nueva_columna] in v:
                setPixelesAdyacentes.add((nueva_fila, nueva_columna)) 
    return setPixelesAdyacentes
    
def adj4(img, pixelCoord, v) -> set:
    return adj(img, pixelCoord, v, [(0, 1), (1, 0), (0, -1), (-1, 0)])

def adjD(img, pixelCoord, v) -> set:
    return adj(img, pixelCoord, v, [(1,1), (-1, -1), (1, -1), (-1, 1)])

def adj8(img, pixelCoord, v) -> set:
    return adj(img, pixelCoord, v, [(0, 1), (1, 0), (0, -1), (-1, 0), (1,1), (-1, -1), (1, -1), (-1, 1)])

def adjm(img, pixelCoord, v) -> set:
    adj4_set = adj4(img, pixelCoord, v)
    adj8_set = adj8(img, pixelCoord, v)
    for pixel in adj8_set:
        if pixel not in adj4_set:
            x, y = pixel
            adj4_pixel_set = adj4(img, (x, y), v)
            if len(adj4_pixel_set & adj4_set) > 0:
                adj4_set.add(pixel)
    return adj4_set

print(img)
print(adj4(img, (2,1), {x for x in range(0,10)}))
print(adj8(img, (2,1), {x for x in range(0,10)}))
print(adjm(img, (2,1), {x for x in range(0,10)}))

[[ 2 13 13]
 [11  4 14]
 [12 12 13]
 [11  1 11]
 [14 14 12]]
fila: 2, columna: 1 = 12
{(3, 1), (1, 1)}
fila: 2, columna: 1 = 12
{(3, 1), (1, 1)}
fila: 2, columna: 1 = 12
fila: 2, columna: 1 = 12
{(3, 1), (1, 1)}
